### ISSUE TITLE
Падает на демонстрации

### ISSUE THREAD

**Issue by bonvech** [spiritiez/dracula-s_castle#1]
![Screenshot_20230317_164322](https://user-images.githubusercontent.com/20185626/225922429-bb91e88e-6d79-420f-803d-2abdab8b2950.png)

**Comment by bonvech** [comment]
И тут тоже падает:
![Screenshot_20230317_165350](https://user-images.githubusercontent.com/20185626/225925234-b3204627-15bc-404e-9e87-5383d7b2a1e1.png)

**Comment by spiritiez** [comment]
Здравствуйте! Спасибо за найденные ошибки! Над первой уже работаю. Вторая произошло из-за того что вы неправильно ввели действие (Enter the castleEnter the castle вместо Enter the castle)

**Comment by spiritiez** [comment]
> дравствуйте! Спасибо за найденные ошибки! Над первой уже работаю. Вторая произошло из-за того что вы неправильно ввели действие (Enter the castleEnter the castle вместо Enter the castle)
